"""phase2 ingestion tables

Revision ID: d4c8b9a637ce
Revises: 3b5bc6ff9e10
Create Date: 2026-06-25 09:25:19.125367

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd4c8b9a637ce'
down_revision: Union[str, Sequence[str], None] = '3b5bc6ff9e10'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pipeline_runs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('period_from', sa.Date(), nullable=True),
    sa.Column('period_to', sa.Date(), nullable=True),
    sa.Column('status', sa.String(length=12), nullable=False),
    sa.Column('thresholds', sa.JSON(), nullable=True),
    sa.Column('upload_ids', sa.JSON(), nullable=True),
    sa.Column('n_day_records', sa.Integer(), nullable=True),
    sa.Column('n_employees', sa.Integer(), nullable=True),
    sa.Column('error_text', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('uploads',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('source', sa.String(length=20), nullable=False),
    sa.Column('stored_path', sa.String(length=500), nullable=False),
    sa.Column('uploaded_by', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=12), nullable=False),
    sa.Column('error_text', sa.Text(), nullable=True),
    sa.Column('uploaded_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['uploaded_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('access_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('run_id', sa.Integer(), nullable=False),
    sa.Column('employee_id', sa.Integer(), nullable=True),
    sa.Column('raw_name', sa.String(length=255), nullable=False),
    sa.Column('event_ts', sa.DateTime(), nullable=False),
    sa.Column('kind', sa.String(length=10), nullable=False),
    sa.Column('source', sa.String(length=10), nullable=False),
    sa.Column('system', sa.String(length=20), nullable=True),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ),
    sa.ForeignKeyConstraint(['run_id'], ['pipeline_runs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('access_events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_access_events_employee_id'), ['employee_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_access_events_run_id'), ['run_id'], unique=False)

    op.create_table('day_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('run_id', sa.Integer(), nullable=False),
    sa.Column('employee_id', sa.Integer(), nullable=False),
    sa.Column('work_date', sa.String(length=10), nullable=False),
    sa.Column('is_weekend', sa.Boolean(), nullable=False),
    sa.Column('int_entry', sa.String(length=5), nullable=True),
    sa.Column('int_exit', sa.String(length=5), nullable=True),
    sa.Column('lez_entry', sa.String(length=5), nullable=True),
    sa.Column('lez_exit', sa.String(length=5), nullable=True),
    sa.Column('entry', sa.String(length=5), nullable=True),
    sa.Column('exit', sa.String(length=5), nullable=True),
    sa.Column('entry_source', sa.String(length=10), nullable=True),
    sa.Column('exit_source', sa.String(length=10), nullable=True),
    sa.Column('start_fixed', sa.Boolean(), nullable=False),
    sa.Column('original_start', sa.String(length=5), nullable=True),
    sa.Column('raw_hours', sa.Numeric(precision=6, scale=2), nullable=False),
    sa.Column('lunch_deducted', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('worked_hours', sa.Numeric(precision=6, scale=2), nullable=False),
    sa.Column('schedule_code', sa.String(length=64), nullable=True),
    sa.Column('dept_name', sa.String(length=255), nullable=True),
    sa.Column('cabinet', sa.String(length=64), nullable=True),
    sa.Column('lez_controlled', sa.Boolean(), nullable=False),
    sa.Column('dual_tracked', sa.Boolean(), nullable=False),
    sa.Column('day_norm', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('absence', sa.String(length=20), nullable=True),
    sa.Column('lateness_min', sa.Integer(), nullable=False),
    sa.Column('overtime_h', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('deviations', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ),
    sa.ForeignKeyConstraint(['run_id'], ['pipeline_runs.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('run_id', 'employee_id', 'work_date', name='uq_day_run_emp_date')
    )
    with op.batch_alter_table('day_records', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_day_records_employee_id'), ['employee_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_day_records_run_id'), ['run_id'], unique=False)

    op.create_table('period_summaries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('run_id', sa.Integer(), nullable=False),
    sa.Column('employee_id', sa.Integer(), nullable=False),
    sa.Column('schedule_code', sa.String(length=64), nullable=True),
    sa.Column('dept_name', sa.String(length=255), nullable=True),
    sa.Column('worked_total', sa.Numeric(precision=8, scale=2), nullable=False),
    sa.Column('credited_total', sa.Numeric(precision=8, scale=2), nullable=False),
    sa.Column('period_norm', sa.Numeric(precision=8, scale=2), nullable=False),
    sa.Column('absence_days', sa.JSON(), nullable=False),
    sa.Column('late_count', sa.Integer(), nullable=False),
    sa.Column('late_minutes', sa.Integer(), nullable=False),
    sa.Column('overtime_total', sa.Numeric(precision=7, scale=2), nullable=False),
    sa.Column('percent', sa.Numeric(precision=6, scale=1), nullable=False),
    sa.Column('bucket', sa.String(length=10), nullable=True),
    sa.Column('overtime_pay', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ),
    sa.ForeignKeyConstraint(['run_id'], ['pipeline_runs.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('run_id', 'employee_id', name='uq_period_run_emp')
    )
    with op.batch_alter_table('period_summaries', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_period_summaries_employee_id'), ['employee_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_period_summaries_run_id'), ['run_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('period_summaries', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_period_summaries_run_id'))
        batch_op.drop_index(batch_op.f('ix_period_summaries_employee_id'))

    op.drop_table('period_summaries')
    with op.batch_alter_table('day_records', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_day_records_run_id'))
        batch_op.drop_index(batch_op.f('ix_day_records_employee_id'))

    op.drop_table('day_records')
    with op.batch_alter_table('access_events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_access_events_run_id'))
        batch_op.drop_index(batch_op.f('ix_access_events_employee_id'))

    op.drop_table('access_events')
    op.drop_table('uploads')
    op.drop_table('pipeline_runs')
    # ### end Alembic commands ###
